### PR TITLE
Expose a public API for training

### PR DESCRIPTION
**Pull request by dae**

### CODE REVIEW

**Comment by dae** [comment]
This is still a work in progress, but assuming you approve, this should be safe to merge as-is. Doing so will help prevent merge conflicts, as I moved all the tests around.

**Review by L-M-Sherlock — APPROVED** [review]
I have run the test in my device, too. Looks good to me.

**Comment by dae** [comment]
Should I change freeze_weights to false?

**Comment by L-M-Sherlock** [comment]
Yup, please set it to true.

**Comment by L-M-Sherlock** [comment]
Main: 

image

This PR:

image

**Comment by dae** [comment]
I tested quite a few times, and was able to trigger it only once. Does it happen repeatedly for you? I suspect it's related to https://github.com/burn-rs/burn/commit/9f1a68bc33508bfbfa91ba7e74cf3ee05ca26f22

**Comment by L-M-Sherlock** [comment]
> Does it happen repeatedly for you?

I meet it every time. And I find that the cost time also decreases. I'm afraid that some samples are dropped.

**Comment by L-M-Sherlock** [comment]
When num_epochs=1, the test result is more weird.
    #[config(default = 1)]
    pub num_epochs: usize,

image

**Comment by L-M-Sherlock** [comment]
Note: only happens in `cargo test --release`.

**Comment by dae** [comment]
Some speedup is expected, because the validation step no longer has any elements, so we save time on that part. I suspect it's just an issue with updating the UI. Try this patch to see more detailed status output:

```diff
diff --git a/src/training.rs b/src/training.rs
index 0962877..6543cd2 100644
--- a/src/training.rs
+++ b/src/training.rs
@@ -141,6 +141,7 @@ impl DashboardRenderer for ProgressCollector {
         info.epoch_total = item.epoch_total;
         info.items_processed = item.progress.items_processed;
         info.items_total = item.progress.items_total;
+        dbg!(&info);
     }
 
     fn render_valid(&mut self, _item: TrainingProgress) {}
@@ -150,7 +151,7 @@ impl DashboardRenderer for ProgressCollector {
 pub(crate) struct TrainingConfig {
     pub model: ModelConfig,
     pub optimizer: AdamConfig,
-    #[config(default = 10)]
+    #[config(default = 1)]
     pub num_epochs: usize,
     #[config(default = 512)]
     pub batch_size: usize,
@@ -275,8 +276,8 @@ mod tests {
             anki21_sample_file_converted_to_fsrs(),
             &config,
             device,
-            None,
-            Some(artifact_dir),
+            Some(ProgressCollector::default()),
+            None, // Some(artifact_dir),
         );
 
         config
```

Run with:

```
cargo test --release -- --nocapture train
```

What does the last page of text say?

**Comment by L-M-Sherlock** [comment]
```
running 1 test
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 512,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 1024,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 1536,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 2048,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 2560,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 3072,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 3584,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 4096,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 4608,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 5120,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 5632,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 6144,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 6656,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 7168,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 7680,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 8192,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 8704,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 9216,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 9728,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 10240,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 10752,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 11264,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 11776,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 12288,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 12800,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 13312,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 13824,
    items_total: 14290,
}
[src/training.rs:144] &info = ProgressInfo {
    epoch: 1,
    epoch_total: 1,
    items_processed: 14290,
    items_total: 14290,
}
test training::tests::training ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.12s
```

**Comment by dae** [comment]
Yeah, so that looks ok to me. Presumably the output weights before and after this PR are the same? Are you on an M1 Mac? Maybe I'll have more luck reproducing this with one of those.

**Comment by dae** [comment]
Another thing you could try: adding a dbg!(_state) to render_valid()

**Comment by dae** [comment]
Reproduced on an M1 machine :+1: Investigating.

**Comment by L-M-Sherlock** [comment]
> Presumably the output weights before and after this PR are the same

They are the same. Maybe we can merge it at first, and open a new issue to keep track of the problem I mention above.

**Comment by dae** [comment]
I've found the problem, it's just a bug in burn's progress display code, and I'll send a fix there.

**Comment by dae** [comment]
:+1: on merging now

**Pull request merged**
