### PR TITLE
Add clippy to CI checks

### PR DESCRIPTION
**Pull request by dae**

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
test dataset::test_from_json ... FAILED

The test json file doesn't match the current FSRSItem structure. I plan to remove it and upload a public collection.anki2 file for test.

**Comment by dae** [comment]
Sounds good - if it contains a small amount of data, we can enable 'cargo test' in CI as well

**Comment by L-M-Sherlock** [comment]
My collection have 330k revlogs. After remove unused table, the collection file's size is 12.3MB.

**Comment by dae** [comment]
It's best not to add large files to the git history. I'd recommend just doing a couple of reviews in a new profile and saving that file into the repo.

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
