### PR TITLE
Create LICENSE

### LINKED ISSUE #43: Add license
@L-M-Sherlock I presume this will be licensed as MIT like your other repos; if so, please add this line to the Cargo.toml file, and add the LICENSE file to the repo:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index c9cd01d..6d8e711 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -2,6 +2,7 @@
 name = "fsrs-optimizer-rs"
 version = "0.1.0"
 edition = "2021"
+license = "MIT"
```

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Close #43

### CODE REVIEW

**Comment by dae** [comment]
Needs a `license = "BSD-3"` line in Cargo.toml, and will need confirmation from the other contributors before merging (https://github.com/open-spaced-repetition/fsrs-optimizer-burn/issues/43#issuecomment-1698558590)

**Review by asukaminato0721 — APPROVED** [review]

**Comment by dae** [comment]
Thanks @asukaminato0721! Because approving a pull request is a little ambiguous, it would be great if you could confirm in a comment that you're happy to license your past contributions under the BSD-3 license.

**Comment by L-M-Sherlock** [comment]
I think it's ready to merge? All contributors have responded in their way.

**Comment by asukaminato0721** [comment]
I am happy to license my past contributions under the BSD-3 license.

**Review by dae — APPROVED** [review]

**Pull request merged**
